# Generated by Django 4.2.11 on 2026-05-29 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(default='award', help_text='Lucide icon name', max_length=50)),
                ('color', models.CharField(default='amber', help_text='Tailwind color name', max_length=20)),
                ('criteria_type', models.CharField(choices=[('TOTAL_XP', 'Total XP'), ('LEVEL', 'Level tertentu'), ('STREAK', 'Streak tertentu'), ('QUEST_COUNT', 'Jumlah quest selesai')], max_length=20)),
                ('threshold', models.PositiveIntegerField(help_text='Value needed to unlock (e.g. 1000 XP, 7 day streak)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'threshold'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='badges.badge')),
            ],
            options={
                'ordering': ['-unlocked_at'],
            },
        ),
    ]
